Repository Theseus-Aegis/MissionTemplate, pull requests merged in 2022-02, with the labels that each got.

#67 Add Unit Counter admin tool
  template/admin/initServer.sqf
Labels: feature request

#66 Add Babel for unconscious units
  template/CfgFunctions.hpp
  template/admin/initPlayerLocal.sqf
  template/functions/fn_unconscious.sqf
Labels: feature request

#69 Add smoke and illumination rounds to D30
  scripts/fn_d30Strike.sqf
Labels: enhancement

#70 Automate mission name
  template/admin/initPlayerLocal.sqf
  template/admin/initServer.sqf
  template/initServer.sqf
Labels: enhancement

#68 Add OCAP AAR Functionality
  template/CfgFunctions.hpp
  template/admin/initPlayerLocal.sqf
  template/admin/initServer.sqf
  template/description.ext
  template/functions/fn_aar.sqf
  template/script_component.hpp
Labels: feature request

#72 Compositions - Add Theseus Marker & Set group callsigns
  compositions/contract/TAC%20-%20Contract%20Template/composition.sqe
Labels: enhancement, bug fix
