Repository Theseus-Aegis/MissionTemplate, pull requests merged in 2022-12, with the labels that each got.

#84 Description - Switch Side channel for Global
  template/admin/description.ext
Labels: enhancement, bug fix

#83 Prep template for mission library
  scripts/README.md
  scripts/fn_bomber.sqf
  scripts/fn_caves.sqf
  scripts/fn_connectBatteryToDefusable.sqf
  scripts/fn_d30Strike.sqf
  scripts/fn_forceShooting.sqf
  scripts/fn_mortarStrike.sqf
  scripts/fn_respiratorEffects.sqf
  scripts/fn_switchAction.sqf
  scripts/fn_teleport.sqf
  scripts/fn_toggleLights.sqf
  template/CfgFunctions.hpp
  template/admin/description.ext
  template/admin/init.sqf
  template/admin/initPlayerLocal.sqf
  template/admin/initServer.sqf
  template/admin/script_component.hpp
  template/admin/script_macros_mission.hpp
  template/description.ext
  template/functions/fn_aar.sqf
  template/functions/fn_baseSpectator.sqf
  template/functions/fn_collectIntel.sqf
  template/functions/fn_collectIntelPostInit.sqf
  template/functions/fn_collectIntelPreInit.sqf
  template/functions/fn_godMode.sqf
  template/functions/fn_hunt.sqf
  template/functions/fn_reinforcements.sqf
  template/functions/fn_unconscious.sqf
  template/initPlayerLocal.sqf
  template/script_component.hpp
Labels: enhancement, cleanup

#82 SOG Template
  compositions/contract/TAC-ArcadianBlackPreset/composition.sqe
  compositions/contract/TAC-ArcadianBlackPreset/header.sqe
  compositions/contract/TAC-ArcadianGreenPreset/composition.sqe
  compositions/contract/TAC-ArcadianGreenPreset/header.sqe
  compositions/contract/TAC-ArcadianTanPreset/composition.sqe
  compositions/contract/TAC-ArcadianTanPreset/header.sqe
  compositions/contract/TAC-ContractTemplate/composition.sqe
  compositions/contract/TAC-ContractTemplate/header.sqe
  compositions/contract/TAC-HeliosPreset/composition.sqe
  compositions/contract/TAC-HeliosPreset/header.sqe
  compositions/extra/TAC-20PlayerTrigger/composition.sqe
  compositions/extra/TAC-20PlayerTrigger/header.sqe
  compositions/extra/TAC-BuildingDamage/composition.sqe
  compositions/extra/TAC-BuildingDamage/header.sqe
  compositions/extra/TAC-DoorLocking/composition.sqe
  compositions/extra/TAC-DoorLocking/header.sqe
  compositions/extra/TAC-TriggerBargate/composition.sqe
  compositions/extra/TAC-TriggerBargate/header.sqe
  compositions/sog/TAC-SOGFullArsenal/composition.sqe
  compositions/sog/TAC-SOGFullArsenal/header.sqe
  compositions/sog/TAC-SOGTemplate/composition.sqe
  compositions/sog/TAC-SOGTemplate/header.sqe
  compositions/sog/TAC-SOGZeusTemplate/composition.sqe
  compositions/sog/TAC-SOGZeusTemplate/header.sqe
  template/cba_settings.sqf
  template/script_component.hpp
Labels: feature request

#85 Add `RECOMPILE` and `DFUNC` macros
  template/CfgFunctions.hpp
  template/admin/description.ext
  template/admin/script_macros_mission.hpp
  template/functions/fnc_briefing.sqf
  template/script_component.hpp
Labels: enhancement

#86 Remove severely outdated Mission Making Guide
  .github/workflows/package.yml
  guide/CfgFunctions.hpp
  guide/admin/description.ext
  guide/admin/init.sqf
  guide/admin/initPlayerLocal.sqf
  guide/cba_settings.sqf
  guide/description.ext
  guide/functions/fn_baseSpectator.sqf
  guide/functions/fn_briefing.sqf
  guide/functions/fn_collectIntel.sqf
  guide/functions/fn_collectIntelPostInit.sqf
  guide/functions/fn_collectIntelPreInit.sqf
  guide/functions/fn_godMode.sqf
  guide/functions/fn_reinforcements.sqf
  guide/init.sqf
  guide/initPlayerLocal.sqf
  guide/mission.sqm
  guide/script_component.hpp
Labels: cleanup
